name = "timeflower"
compatibility_date = "2023-01-01"

[build]
command = "hugo"
publish = "public"

[site]
bucket = "./public"

[build.environment]
HUGO_VERSION = "0.118.2"

# Cloudflare Pages 需要这个配置
pages_build_output_dir = "public"