name = "timeflower"
compatibility_date = "2023-01-01"

[build]
command = "hugo --gc --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.118.2"
NODE_VERSION = "18"

pages_build_output_dir = "public"